### ISSUE TITLE
Error when run Navigation.pushReplacement with Stream + Bloc 

### ISSUE THREAD

**Issue by lucassimon** [lucassimon/login_in_flutter#1]
[Stream Builder on Login Screen](https://github.com/lucassimon/login_in_flutter/blob/master/lib/src/login/screen.dart#L23-L28)

[Bloc code](https://github.com/lucassimon/login_in_flutter/blob/master/lib/src/app/bloc.dart)

```dart
Performing hot restart...                                               
Restarted application in 1,564ms.
I/flutter (14094): not_authenticathed
I/art     (14094): Do partial code cache collection, code=30KB, data=24KB
I/art     (14094): After code cache collection, code=30KB, data=24KB
I/art     (14094): Increasing code cache capacity to 128KB
I/flutter (14094): call auth repository with lucassrod@gmail.com and teste123 to do a login
I/flutter (14094): {email: lucassrod@gmail.com, password: teste123}
I/flutter (14094): http://10.0.2.2:5000
I/flutter (14094): loading
I/flutter (14094): save qweqwe.sdfdsf.vbvb on login-in-flutter-token
I/flutter (14094): save dfdf.fdgdfgrere.sdfdfdf on login-in-flutter-refresh
I/flutter (14094): success
I/flutter (14094): should use navigator Push Replacement
I/flutter (14094): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (14094): The following assertion was thrown building StreamBuilder<String>(dirty, state:
I/flutter (14094): _StreamBuilderBaseState<String, AsyncSnapshot<String>>#f96cb):
I/flutter (14094): setState() or markNeedsBuild() called during build.
I/flutter (14094): This Overlay widget cannot be marked as needing to build because the framework is already in the
I/flutter (14094): process of building widgets.  A widget can be marked as needing to be built during the build phase
I/flutter (14094): only if one of its ancestors is currently building. This exception is allowed because the framework
I/flutter (14094): builds parent widgets before children, which means a dirty descendant will always be built.
I/flutter (14094): Otherwise, the framework might not visit this widget during this build phase.
I/flutter (14094): The widget on which setState() or markNeedsBuild() was called was:
I/flutter (14094):   Overlay-[LabeledGlobalKey<OverlayState>#e5080]
I/flutter (14094): The widget which was currently being built when the offending call was made was:
I/flutter (14094):   StreamBuilder<String>
I/flutter (14094): 
I/flutter (14094): When the exception was thrown, this was the stack:
I/flutter (14094): #0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:3670:11)
I/flutter (14094): #1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:3685:6)
I/flutter (14094): #2      State.setState (package:flutter/src/widgets/framework.dart:1161:14)
I/flutter (14094): #3      OverlayState.insertAll (package:flutter/src/widgets/overlay.dart:346:5)
I/flutter (14094): #4      OverlayRoute.install (package:flutter/src/widgets/routes.dart:43:24)
I/flutter (14094): #5      TransitionRoute.install (package:flutter/src/widgets/routes.dart:180:11)
I/flutter (14094): #6      ModalRoute.install (package:flutter/src/widgets/routes.dart:907:11)
I/flutter (14094): #7      NavigatorState.pushReplacement (package:flutter/src/widgets/navigator.dart:1839:14)
I/flutter (14094): #8      Login.build.<anonymous closure> (package:login/src/login/screen.dart:23:37)
I/flutter (14094): #9      StreamBuilder.build (package:flutter/src/widgets/async.dart:425:74)
I/flutter (14094): #10     _StreamBuilderBaseState.build (package:flutter/src/widgets/async.dart:125:48)
I/flutter (14094): #11     StatefulElement.build (package:flutter/src/widgets/framework.dart:4012:27)
I/flutter (14094): #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3924:15)
I/flutter (14094): #13     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter (14094): #14     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2340:33)
I/flutter (14094): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
I/flutter (14094): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
I/flutter (14094): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1016:15)
I/flutter (14094): #18     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:958:9)
I/flutter (14094): #19     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:874:5)
I/flutter (14094): #23     _invoke (dart:ui/hooks.dart:236:10)
I/flutter (14094): #24     _drawFrame (dart:ui/hooks.dart:194:3)
I/flutter (14094): (elided 3 frames from package dart:async)
```

**Comment by lucassimon** [comment]
Refactoring the code to use bloc_pattern package.

I put the context on LoginBloc with setter and after login() called I call the Navigation.of to push to Dashboard();
